apiVersion: v1
kind: PersistentVolume
metadata:
  name: ora-db-pv
spec:
  storageClassName: db-storage
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/github/oradbpv2"

---

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: ora-db-pvc
  namespace: database-namespace
  labels:
spec:
  storageClassName: db-storage
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi

